-- local copilot = {
-- 	"zbirenbaum/copilot.lua",
-- 	dependencies = {
-- 		"copilotlsp-nvim/copilot-lsp", -- (optional) for NES functionality
-- 	},
-- 	cmd = "Copilot",
-- 	event = "InsertEnter",
-- 	opts = {
-- 		filetypes = {
-- 			javascript = true, -- allow specific filetype
-- 			typescript = true, -- allow specific filetype
-- 			markdown = true,
-- 			python = true,
-- 			typst = true,
-- 			rust = true,
-- 			lua = true,
-- 			["*"] = false, -- disable for all other filetypes and ignore default `filetypes`
-- 		},
-- 	},
-- 	config = function()
-- 		require("copilot").setup({
-- 			-- copilot_model = "GPT-5",
-- 		})
-- 	end,
-- }

-- local copilot = {
--   "github/copilot.vim",
--   opts = {
--     filetypes = {
--       javascript = true,
--       typescript = true,
--       markdown = true,
--       python = true,
--       typst = true,
--       rust = true,
--       lua = false,
--       ["*"] = false,
--     },
--   },
--   config = function ()
--
--   end
-- }
return {}
